# Generated by Django 4.1 on 2022-08-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arabic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created',
        ),
    ]
